SELECT QUERY_ID, WAREHOUSE_NAME, BYTES_SCANNED/POW(1024,3) AS gb_scanned,
       TOTAL_ELAPSED_TIME/1000 AS sec, LEFT(QUERY_TEXT, 200) AS txt
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day,-1,CURRENT_TIMESTAMP())
ORDER BY BYTES_SCANNED DESC
LIMIT 20;
