-- Pipe and load health (Snowpipe)
SELECT * FROM TABLE(INFORMATION_SCHEMA.LOAD_HISTORY(
  START_TIME => DATEADD('hour', -6, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;

-- What changed for downstream consumers (both lanes)
SELECT * FROM TABLE(INFORMATION_SCHEMA.STREAMS())
WHERE TABLE_NAME ILIKE 'BRONZE%';

-- Task executions that promote deltas
SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
  SCHEDULED_TIME_RANGE_START => DATEADD('hour', -6, CURRENT_TIMESTAMP())
));
