GRANT APPLY MASKING POLICY, APPLY ROW ACCESS POLICY, APPLY TAG ON ACCOUNT TO ROLE ROLE_GOVERNANCE;

ALTER TABLE core.dim_customer
  MODIFY COLUMN email SET MASKING POLICY mask_email;

ALTER VIEW mart.v_orders ADD ROW ACCESS POLICY rap_tenant ON (tenant_id);
