-- Reader
GRANT USAGE ON DATABASE DB TO ROLE R;
GRANT USAGE ON SCHEMA DB.SCH TO ROLE R;
GRANT SELECT ON ALL VIEWS IN SCHEMA DB.SCH TO ROLE R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DB.SCH TO ROLE R;

-- Writer
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA DB.SCH TO ROLE R;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DB.SCH TO ROLE R;
