CREATE OR REPLACE FUNCTION util.safe_divide(n NUMBER, d NUMBER)
RETURNS FLOAT LANGUAGE SQL AS 'IFF(d=0, NULL, n/d)';

-- Find heavy queries by bytes (last 2h)
SELECT QUERY_ID, BYTES_SCANNED/1e9 AS gb, LEFT(QUERY_TEXT,200)
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(hour,-2,CURRENT_TIMESTAMP())
ORDER BY gb DESC LIMIT 20;
