SELECT AVG((QUEUED_OVERLOAD_TIME+QUEUED_PROVISIONING_TIME)/1000) queued_s,
       AVG(EXECUTION_TIME/1000) exec_s
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(minute,-10,CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME='WH_BI';
