SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) ORDER BY SCHEDULED_TIME DESC LIMIT 20;
SELECT NAME, LAST_REFRESH_TIME, ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY
ORDER BY LAST_REFRESH_TIME DESC LIMIT 20;
