SELECT OBJECTS_USED:objectName::string AS object_name,
       COUNT(*) AS reads
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY,
     LATERAL FLATTEN(INPUT => BASE_OBJECTS_ACCESSED) AS OBJECTS_USED
WHERE QUERY_START_TIME >= DATEADD(day,-14,CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY reads DESC;
