-- Reader for the catalog
CREATE ROLE ROLE_CATALOG_READER;
GRANT USAGE ON DATABASE <DB> TO ROLE ROLE_CATALOG_READER;
GRANT USAGE ON SCHEMA gov_api TO ROLE ROLE_CATALOG_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA gov_api TO ROLE ROLE_CATALOG_READER;

-- Writer (applies curated changes via CI)
CREATE ROLE ROLE_GOVERNANCE_APPLIER;
GRANT APPLY MASKING POLICY, APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE ROLE_GOVERNANCE_APPLIER;
GRANT APPLY TAG ON ACCOUNT TO ROLE ROLE_GOVERNANCE_APPLIER;
