CREATE OR REPLACE VIEW docs.v_badges AS
SELECT
  r.OBJECT_SCHEMA AS sch,
  r.OBJECT_NAME   AS obj,
  STRING_AGG(DISTINCT
    CASE
      WHEN t.TAG_NAME='CLASSIFICATION' AND t.TAG_VALUE LIKE 'pii.%' THEN 'PII'
      ELSE NULL
    END, ', ') AS pii,
  IFF(EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES p
        WHERE p.OBJECT_SCHEMA=r.OBJECT_SCHEMA AND p.OBJECT_NAME=r.OBJECT_NAME
          AND p.POLICY_KIND='MASKING_POLICY'
      ), 'MASKED', '—') AS masking
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES t
RIGHT JOIN SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES r
  ON r.OBJECT_SCHEMA=t.OBJECT_SCHEMA AND r.OBJECT_NAME=t.OBJECT_NAME
GROUP BY 1,2;
