SELECT
  SPLIT_PART(QUERY_TAG,';',1) AS team_kv,
  SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day,-30,CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY credits DESC;
