CREATE OR REPLACE VIEW ops.v_credits_by_team AS
SELECT
  TO_DATE(q.START_TIME) AS day,
  SPLIT_PART(q.QUERY_TAG,';',1) AS team_kv,                -- e.g., 'team=fin'
  SUM(q.CREDITS_USED_COMPUTE + q.CREDITS_USED_CLOUD_SERVICES) AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q
GROUP BY 1,2;
