CREATE OR REPLACE VIEW ops.v_data_transfer AS
SELECT
  TO_DATE(START_TIME) AS day,
  DIRECTION,
  SUM(EGRESS_FROM_SNOWFLAKE_BYTES)/POWER(1024,3) AS egress_gb
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
GROUP BY 1,2;
