SELECT
  COALESCE(OBJECT_TAGS:'COST_CENTER'::string,'unTagged') AS cost_center,
  WAREHOUSE_NAME,
  TO_DATE(START_TIME) AS day,
  SUM(CREDITS_USED)   AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day,-30,CURRENT_TIMESTAMP())
GROUP BY 1,2,3
ORDER BY 1,3,2;
