-- 1) Route users to the correct lane
ALTER ROLE ANALYST    SET DEFAULT_WAREHOUSE = wh_bi;
ALTER ROLE ELT_RUNNER SET DEFAULT_WAREHOUSE = wh_elt;

-- 2) BI lane: elastic, cache-friendly, with a budget
CREATE OR REPLACE RESOURCE MONITOR rm_bi
  WITH CREDIT_QUOTA = 500
  FREQUENCY = MONTHLY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 95 PERCENT DO SUSPEND;

ALTER WAREHOUSE wh_bi SET
  WAREHOUSE_SIZE = 'SMALL',
  MIN_CLUSTER_COUNT = 1,
  MAX_CLUSTER_COUNT = 4,
  SCALING_POLICY = 'STANDARD',
  AUTO_SUSPEND = 90,
  AUTO_RESUME = TRUE,
  RESOURCE_MONITOR = rm_bi;

-- 3) Storage hygiene: reasonable rewind windows
ALTER DATABASE prod  SET DATA_RETENTION_TIME_IN_DAYS = 7;
ALTER SCHEMA   stage SET DATA_RETENTION_TIME_IN_DAYS = 1;  -- transient/intermediate
