CREATE OR REPLACE VIEW ops.v_storage_by_db AS
WITH latest AS (
  SELECT *,
         ROW_NUMBER() OVER (PARTITION BY DATABASE_NAME ORDER BY USAGE_DATE DESC) AS rn
  FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
)
SELECT
  DATABASE_NAME,
  COALESCE(OBJECT_TAGS:'COST_CENTER'::string,'unTagged') AS cost_center,
  (ACTIVE_BYTES+TIME_TRAVEL_BYTES+FAILSAFE_BYTES)/POWER(1024,3) AS total_gb,
  USAGE_DATE
FROM latest WHERE rn=1;
