CREATE TAG IF NOT EXISTS cost_center;

ALTER WAREHOUSE wh_bi SET TAG cost_center='sales_bi';

-- Rollup
SELECT w.WAREHOUSE_NAME, t.TAG_VALUE AS cost_center, TO_DATE(w.START_TIME) AS day, SUM(w.CREDITS_USED) AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY w
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.OBJECT_TAGS t
  ON t.OBJECT_NAME = w.WAREHOUSE_NAME AND t.TAG_NAME='COST_CENTER'
WHERE w.START_TIME >= DATEADD(day,-30,CURRENT_TIMESTAMP())
GROUP BY 1,2,3;
