SELECT DIRECT_OBJECTS_ACCESSED:objectName::string AS object_name,
       COUNT(*) AS reads
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD(day,-7,CURRENT_TIMESTAMP())
  AND OBJECT_NAME LIKE 'PROD_WEATHER.%'
GROUP BY 1
ORDER BY reads DESC;
