CREATE OR REPLACE RESOURCE MONITOR rm_readers
  WITH CREDIT_QUOTA = 200
  FREQUENCY = MONTHLY
  TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE wh_reader_weather SET RESOURCE_MONITOR = rm_readers;
