-- Credits by cost_center via warehouse tag
SELECT
  t.TAG_VALUE AS cost_center,
  TO_DATE(w.START_TIME) AS day,
  SUM(w.CREDITS_USED)   AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY w
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.OBJECT_TAGS t
  ON t.OBJECT_NAME = w.WAREHOUSE_NAME AND t.TAG_NAME='COST_CENTER'
GROUP BY 1,2;
