CREATE SCHEMA IF NOT EXISTS fin;

-- Credits by warehouse/day
CREATE OR REPLACE VIEW fin.v_credits_daily AS
SELECT
  WAREHOUSE_NAME,
  TO_DATE(START_TIME) AS day,
  SUM(CREDITS_USED)   AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY 1,2;

-- Storage composition (latest snapshot per DB)
CREATE OR REPLACE VIEW fin.v_storage_now AS
WITH latest AS (
  SELECT *,
         ROW_NUMBER() OVER (PARTITION BY DATABASE_NAME ORDER BY USAGE_DATE DESC) rn
  FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
)
SELECT DATABASE_NAME,
       ACTIVE_BYTES, TIME_TRAVEL_BYTES, FAILSAFE_BYTES
FROM latest WHERE rn=1;
