-- Cap an ad-hoc lane daily; notify then suspend
CREATE OR REPLACE RESOURCE MONITOR rm_ad_hoc
  WITH CREDIT_QUOTA = 100
  FREQUENCY = DAILY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE wh_ad_hoc SET
  RESOURCE_MONITOR = rm_ad_hoc,
  STATEMENT_TIMEOUT_IN_SECONDS = 900,
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300,
  AUTO_SUSPEND = 120,
  AUTO_RESUME = TRUE;
