-- Today vs 7-day median per warehouse
WITH d AS (
  SELECT TO_DATE(START_TIME) day, WAREHOUSE_NAME, SUM(CREDITS_USED) credits
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE START_TIME >= DATEADD(day,-14,CURRENT_TIMESTAMP())
  GROUP BY 1,2
),
b AS (
  SELECT WAREHOUSE_NAME, MEDIAN(credits) AS med7
  FROM d WHERE day < CURRENT_DATE() GROUP BY 1
)
SELECT d.WAREHOUSE_NAME, d.credits AS today, b.med7, today - med7 AS delta
FROM d JOIN b USING (WAREHOUSE_NAME)
WHERE d.day = CURRENT_DATE()
ORDER BY delta DESC;

-- Top bytes scanned (last 2h)
SELECT QUERY_ID, USER_NAME, WAREHOUSE_NAME,
       BYTES_SCANNED/POWER(1024,3) AS gb_scanned,
       TOTAL_ELAPSED_TIME/1000     AS sec
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(hour,-2,CURRENT_TIMESTAMP())
ORDER BY BYTES_SCANNED DESC
LIMIT 20;
