-- Credits by warehouse (and tag) in the last 30 days
SELECT
  WAREHOUSE_NAME,
  TO_DATE(START_TIME) AS day,
  SUM(CREDITS_USED)   AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY 1,2
ORDER BY 2,1;

-- Attribution by query tag
SELECT
  SPLIT_PART(QUERY_TAG, ';', 1) AS team_kv,
  SUM(CREDITS_USED_CLOUD_SERVICES + CREDITS_USED_COMPUTE) AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY credits DESC;
