-- Is time spent waiting or working?
SELECT
  WAREHOUSE_NAME,
  AVG((QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME)/1000) AS avg_queued_s,
  AVG(EXECUTION_TIME/1000) AS avg_exec_s
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
  END_TIME_RANGE_START => DATEADD('hour', -2, CURRENT_TIMESTAMP())
))
GROUP BY 1
ORDER BY avg_queued_s DESC;

-- Did scaling actually add lanes when needed?
SELECT *
FROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_LOAD_HISTORY(
  WAREHOUSE_NAME => 'WH_BI',
  START_TIME => DATEADD('hour', -2, CURRENT_TIMESTAMP())
))
ORDER BY START_TIME;
