-- BI lane: warn early, suspend before runaway
CREATE OR REPLACE RESOURCE MONITOR rm_bi
  WITH CREDIT_QUOTA = 500
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 95 PERCENT DO SUSPEND
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE wh_bi SET RESOURCE_MONITOR = rm_bi;

-- ELT lane: bigger budget, same pattern
CREATE OR REPLACE RESOURCE MONITOR rm_elt
  WITH CREDIT_QUOTA = 1200
  FREQUENCY = MONTHLY
  TRIGGERS ON 85 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE wh_elt SET RESOURCE_MONITOR = rm_elt;
