-- BI: elastic, cache-friendly
CREATE WAREHOUSE wh_bi
  WAREHOUSE_SIZE = 'SMALL'
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 4
  SCALING_POLICY = 'STANDARD'
  AUTO_SUSPEND = 90
  AUTO_RESUME = TRUE;

-- ELT: muscle for heavy steps; no multi-cluster
CREATE WAREHOUSE wh_elt
  WAREHOUSE_SIZE = 'LARGE'
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 1
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  SCALING_POLICY = 'ECONOMY';
