-- Inside PROD_SALES
CREATE DATABASE ROLE IF NOT EXISTS DBR_SALES_READ_MART;
GRANT USAGE ON SCHEMA PROD_SALES.MART TO DATABASE ROLE DBR_SALES_READ_MART;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROD_SALES.MART TO DATABASE ROLE DBR_SALES_READ_MART;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROD_SALES.MART TO DATABASE ROLE DBR_SALES_READ_MART;

-- Let an account role use the DB role
GRANT DATABASE ROLE DBR_SALES_READ_MART TO ROLE ROLE_DATA_READER_SALES;
