-- Apply policies & tags (account-level)
GRANT APPLY MASKING POLICY     ON ACCOUNT TO ROLE ROLE_GOVERNANCE;
GRANT APPLY ROW ACCESS POLICY  ON ACCOUNT TO ROLE ROLE_GOVERNANCE;
GRANT APPLY TAG                ON ACCOUNT TO ROLE ROLE_GOVERNANCE;

-- Visibility into usage (optional)
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ROLE_GOVERNANCE;
