-- Re-assert reader rights (safe to run daily)
GRANT USAGE ON DATABASE PROD_SALES TO ROLE ROLE_DATA_READER_SALES;
GRANT USAGE ON SCHEMA   PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;
GRANT SELECT ON ALL VIEWS   IN SCHEMA PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;
