-- Tag columns
CREATE TAG IF NOT EXISTS classification;
ALTER TABLE PROD_SALES.CORE.DIM_CUSTOMER
  MODIFY COLUMN EMAIL SET TAG classification = 'pii.email';

-- Governance job attaches the right policy where tag == 'pii.*'
-- (RUN BY ROLE_GOVERNANCE)
ALTER TABLE PROD_SALES.CORE.DIM_CUSTOMER
  MODIFY COLUMN EMAIL SET MASKING POLICY MASK_EMAIL;

-- Tenant/region scoping
CREATE OR REPLACE ROW ACCESS POLICY RAP_TENANT AS (tenant_id STRING)
RETURNS BOOLEAN ->
  EXISTS (SELECT 1 FROM GOV.USER_TENANTS u WHERE u.USER_NAME = CURRENT_USER() AND u.TENANT_ID = tenant_id);

ALTER VIEW PROD_SALES.MART.V_ORDERS ADD ROW ACCESS POLICY RAP_TENANT ON (tenant_id);
