-- Allow ops to monitor & run tasks in OPS
GRANT USAGE ON SCHEMA PROD_SALES.OPS TO ROLE ROLE_PLATFORM_OPS;
GRANT MONITOR, OPERATE ON ACCOUNT TO ROLE ROLE_PLATFORM_OPS;

-- Task/pipe execution (schema-level)
GRANT EXECUTE TASK ON SCHEMA PROD_SALES.OPS TO ROLE ROLE_PLATFORM_OPS;
