GRANT USAGE ON DATABASE PROD_SALES TO ROLE ROLE_DATA_READER_SALES;
GRANT USAGE ON SCHEMA   PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;

GRANT SELECT ON ALL VIEWS  IN SCHEMA PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;

-- If marts include tables (not just views):
GRANT SELECT ON ALL TABLES  IN SCHEMA PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_SALES.MART TO ROLE ROLE_DATA_READER_SALES;

-- Extend to BI/Analyst
GRANT ROLE ROLE_DATA_READER_SALES TO ROLE ROLE_BI_APP;
GRANT ROLE ROLE_BI_APP            TO ROLE ROLE_ANALYST;
