-- Platform & governance
CREATE ROLE IF NOT EXISTS ROLE_PLATFORM_OPS;
CREATE ROLE IF NOT EXISTS ROLE_GOVERNANCE;

GRANT ROLE ROLE_PLATFORM_OPS TO ROLE SYSADMIN;
GRANT ROLE ROLE_GOVERNANCE  TO ROLE SECURITYADMIN;

-- Domain
CREATE ROLE IF NOT EXISTS ROLE_DATA_ADMIN_SALES;
CREATE ROLE IF NOT EXISTS ROLE_ELT_WRITER_SALES;
CREATE ROLE IF NOT EXISTS ROLE_DATA_READER_SALES;
CREATE ROLE IF NOT EXISTS ROLE_BI_APP;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;

GRANT ROLE ROLE_BI_APP          TO ROLE ROLE_ANALYST;
