-- Create database & schemas (by SYSADMIN)
CREATE DATABASE IF NOT EXISTS PROD_SALES;
CREATE SCHEMA   IF NOT EXISTS PROD_SALES.STAGE;
CREATE SCHEMA   IF NOT EXISTS PROD_SALES.CORE;
CREATE SCHEMA   IF NOT EXISTS PROD_SALES.MART;
CREATE SCHEMA   IF NOT EXISTS PROD_SALES.OPS;

-- Domain admin owns schemas
GRANT OWNERSHIP ON SCHEMA PROD_SALES.STAGE TO ROLE ROLE_DATA_ADMIN_SALES COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_SALES.CORE  TO ROLE ROLE_DATA_ADMIN_SALES COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_SALES.MART  TO ROLE ROLE_DATA_ADMIN_SALES COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_SALES.OPS   TO ROLE ROLE_DATA_ADMIN_SALES COPY CURRENT GRANTS;

-- Base usage
GRANT USAGE ON DATABASE PROD_SALES TO ROLE ROLE_DATA_ADMIN_SALES;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD_SALES TO ROLE ROLE_DATA_ADMIN_SALES;
