-- BI lane
CREATE WAREHOUSE IF NOT EXISTS WH_BI WITH WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=120 AUTO_RESUME=TRUE;
GRANT USAGE, OPERATE ON WAREHOUSE WH_BI TO ROLE ROLE_BI_APP;

-- ELT lane
CREATE WAREHOUSE IF NOT EXISTS WH_ELT_SALES WITH WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=300 AUTO_RESUME=TRUE;
GRANT USAGE, OPERATE ON WAREHOUSE WH_ELT_SALES TO ROLE ROLE_ELT_WRITER_SALES;
