GRANT USAGE ON DATABASE PROD_SALES TO ROLE ROLE_ELT_WRITER_SALES;
GRANT USAGE ON SCHEMA   PROD_SALES.STAGE TO ROLE ROLE_ELT_WRITER_SALES;
GRANT USAGE ON SCHEMA   PROD_SALES.CORE  TO ROLE ROLE_ELT_WRITER_SALES;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES  IN SCHEMA PROD_SALES.STAGE TO ROLE ROLE_ELT_WRITER_SALES;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_SALES.STAGE TO ROLE ROLE_ELT_WRITER_SALES;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES  IN SCHEMA PROD_SALES.CORE  TO ROLE ROLE_ELT_WRITER_SALES;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_SALES.CORE TO ROLE ROLE_ELT_WRITER_SALES;

GRANT USAGE ON ALL SEQUENCES  IN SCHEMA PROD_SALES.CORE  TO ROLE ROLE_ELT_WRITER_SALES;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA PROD_SALES.CORE TO ROLE ROLE_ELT_WRITER_SALES;
