SELECT VALUE:clientApplication::string AS client_app,
       COUNT(*) AS queries
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY,
     LATERAL FLATTEN(input => CLIENT_ENVIRONMENT)
WHERE START_TIME >= DATEADD(day,-30,CURRENT_TIMESTAMP())
  AND DATABASE_NAME='DATASET'  -- your shared DB/schema
GROUP BY 1
ORDER BY queries DESC;
