CREATE OR REPLACE RESOURCE MONITOR rm_reader_acme
  WITH CREDIT_QUOTA = 100
  FREQUENCY = MONTHLY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE wh_reader_acme SET RESOURCE_MONITOR = rm_reader_acme;
