SELECT QUERY_START_TIME, USER_NAME, ROLE_NAME, DIRECT_OBJECTS_ACCESSED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD(day,-7,CURRENT_TIMESTAMP())
  AND ARRAY_EXISTS(DIRECT_OBJECTS_ACCESSED, x -> x:objectName::string LIKE 'DATASET.V_TRIPS_V1');
