CREATE OR REPLACE VIEW gov.v_object_lineage AS
SELECT REFERENCING_OBJECT_DATABASE  AS db,
       REFERENCING_OBJECT_SCHEMA    AS sch,
       REFERENCING_OBJECT_NAME      AS obj,
       REFERENCED_OBJECT_DATABASE   AS src_db,
       REFERENCED_OBJECT_SCHEMA     AS src_sch,
       REFERENCED_OBJECT_NAME       AS src_obj,
       REFERENCED_OBJECT_DOMAIN     AS src_type
FROM <db>.<schema>.INFORMATION_SCHEMA.OBJECT_DEPENDENCIES;

CREATE OR REPLACE VIEW gov.v_pii_usage AS
SELECT a.QUERY_ID, a.QUERY_START_TIME, a.USER_NAME, a.ROLE_NAME,
       r.OBJECT_DATABASE, r.OBJECT_SCHEMA, r.OBJECT_NAME, r.COLUMN_NAME, r.TAG_VALUE AS classification
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY a
JOIN SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES r
  ON r.OBJECT_NAME = a.DIRECT_OBJECTS_ACCESSED:objectName::string
WHERE r.TAG_NAME = 'CLASSIFICATION';
