-- Upstream/downstream structure for a view
SELECT REFRESHED_ON, REFERENCED_OBJECT_NAME, REFERENCED_OBJECT_DOMAIN, REFERENCING_OBJECT_NAME
FROM <db>.<schema>.INFORMATION_SCHEMA.OBJECT_DEPENDENCIES
WHERE REFERENCING_OBJECT_NAME = 'V_SALES_MART';

-- Who read table X in the last 7 days
SELECT QUERY_ID, DIRECT_OBJECTS_ACCESSED, BASE_OBJECTS_ACCESSED, QUERY_START_TIME, ROLE_NAME, USER_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD(day,-7,CURRENT_TIMESTAMP())
  AND ARRAY_CONTAINS('CORE.DIM_CUSTOMER', PARSE_JSON(BASE_OBJECTS_ACCESSED));

-- Tag coverage report
SELECT OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME,
       TAG_NAME, TAG_VALUE, MODIFIED
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE TAG_NAME IN ('CLASSIFICATION','OWNER')
ORDER BY OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME;
