SELECT t.OBJECT_DATABASE, t.OBJECT_SCHEMA, t.OBJECT_NAME, t.COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES t
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES p
  ON p.OBJECT_DATABASE = t.OBJECT_DATABASE
 AND p.OBJECT_SCHEMA   = t.OBJECT_SCHEMA
 AND p.OBJECT_NAME     = t.OBJECT_NAME
 AND COALESCE(p.COLUMN_NAME,'') = COALESCE(t.COLUMN_NAME,'')
WHERE t.TAG_NAME = 'CLASSIFICATION'
  AND t.TAG_VALUE LIKE 'pii.%'
  AND p.POLICY_NAME IS NULL;
