SELECT QUERY_ID, QUERY_START_TIME, USER_NAME, ROLE_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD(day,-7,CURRENT_TIMESTAMP())
  AND ARRAY_CONTAINS('MART.FACT_EVENTS', PARSE_JSON(BASE_OBJECTS_ACCESSED));
