SELECT *
FROM TABLE(INFORMATION_SCHEMA.LOAD_HISTORY(
  TABLE_NAME => 'ORDERS',
  START_TIME => DATEADD('hour', -6, CURRENT_TIMESTAMP())
));

-- If you allowed errors:
SELECT *
FROM TABLE(VALIDATE(
  TABLE_NAME => 'RAW.ORDERS',
  JOB_ID     => LAST_QUERY_ID()
));
