WITH latest AS (
  SELECT *,
         ROW_NUMBER() OVER (PARTITION BY DATABASE_NAME ORDER BY USAGE_DATE DESC) rn
  FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
)
SELECT DATABASE_NAME,
       ACTIVE_BYTES/POWER(1024,3)      AS active_gb,
       TIME_TRAVEL_BYTES/POWER(1024,3) AS tt_gb,
       FAILSAFE_BYTES/POWER(1024,3)    AS fs_gb
FROM latest
WHERE rn = 1
ORDER BY (active_gb + tt_gb + fs_gb) DESC;
