SELECT QUERY_ID, USER_NAME, WAREHOUSE_NAME,
       BYTES_SCANNED/POWER(1024,3) AS gb_scanned,
       TOTAL_ELAPSED_TIME/1000     AS elapsed_s
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(minute, -15, CURRENT_TIMESTAMP())
  AND BYTES_SCANNED > 200*POWER(1024,3)  -- >200 GB
ORDER BY BYTES_SCANNED DESC
LIMIT 20;
