SELECT QUERY_ID, USER_NAME, WAREHOUSE_NAME,
       BYTES_SCANNED/POWER(1024,3) AS gb_scanned,
       TOTAL_ELAPSED_TIME/1000     AS elapsed_s,
       QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day, -1, CURRENT_TIMESTAMP())
ORDER BY BYTES_SCANNED DESC
LIMIT 20;
