SELECT
  WAREHOUSE_NAME,
  TO_DATE(START_TIME) AS day,
  SUM(CREDITS_USED)   AS credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY 1,2
ORDER BY 2,1;
