WITH q AS (
  SELECT (QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME)/1000.0 AS queued_s,
         EXECUTION_TIME/1000.0 AS exec_s
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD(minute,-10,CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME = 'WH_BI'
    AND QUERY_TYPE IN ('SELECT')  -- optional narrowing
),
p AS (
  SELECT
    APPROX_PERCENTILE(queued_s, 0.95) AS p95_queued,
    APPROX_PERCENTILE(exec_s,   0.95) AS p95_exec
  FROM q
)
SELECT * FROM p;
