SELECT a.QUERY_START_TIME, a.USER_NAME, a.ROLE_NAME,
       r.OBJECT_DATABASE, r.OBJECT_SCHEMA, r.OBJECT_NAME, r.COLUMN_NAME, r.TAG_VALUE AS classification
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY a
JOIN SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES r
  ON r.OBJECT_NAME = a.DIRECT_OBJECTS_ACCESSED:objectName::string
WHERE a.QUERY_START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND r.TAG_NAME = 'CLASSIFICATION'
  AND r.TAG_VALUE LIKE 'pii.%'
ORDER BY a.QUERY_START_TIME DESC;
