CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE IF NOT EXISTS ops.t_credits_daily AS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY WHERE 1=0;

-- Incremental load pattern (idempotent)
MERGE INTO ops.t_credits_daily t
USING (
  SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE START_TIME >= DATEADD(day, -2, CURRENT_TIMESTAMP())
) s
ON t.START_TIME = s.START_TIME
AND t.WAREHOUSE_ID = s.WAREHOUSE_ID
WHEN MATCHED THEN UPDATE SET CREDITS_USED = s.CREDITS_USED
WHEN NOT MATCHED THEN INSERT VALUES (s.START_TIME, s.WAREHOUSE_ID, s.WAREHOUSE_NAME, s.CREDITS_USED);

-- A simple view SREs can memorize
CREATE OR REPLACE VIEW ops.v_bi_load AS
SELECT TO_DATE(START_TIME) AS day, WAREHOUSE_NAME,
       SUM(CREDITS_USED) AS credits
FROM ops.t_credits_daily
GROUP BY 1,2;
