SELECT ACCOUNT_NAME,
       USAGE_DATE AS day,
       SUM(CREDITS_USED) AS credits
FROM SNOWFLAKE.ORGANIZATION_USAGE.METERING_DAILY_HISTORY
WHERE USAGE_DATE >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY 1,2
ORDER BY 2,1;
