SELECT COUNT(*) AS unmasked_reads
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY a
JOIN SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES t
  ON t.OBJECT_NAME = a.DIRECT_OBJECTS_ACCESSED:objectName::string
WHERE a.QUERY_START_TIME >= DATEADD(day,-1,CURRENT_TIMESTAMP())
  AND t.TAG_NAME = 'CLASSIFICATION'
  AND t.TAG_VALUE LIKE 'pii.%'
  AND a.ROLE_NAME NOT IN ('ROLE_PII_READER','SECURITYADMIN');
