SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, DATEDIFF(minute, SCHEDULED_TIME, COMPLETED_TIME) AS mins
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE NAME = 'elt_refresh_fact_orders'
ORDER BY SCHEDULED_TIME DESC
LIMIT 1;
