-- Tasks that failed in the last run
SELECT NAME, DATABASE_NAME, SCHEMA_NAME, STATE, RETURN_VALUE, SCHEDULED_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATABASE_NAME, SCHEMA_NAME, NAME ORDER BY SCHEDULED_TIME DESC)=1
AND STATE IN ('FAILED','CANCELLED','SUSPENDED');

-- Optional: dynamic table refresh issues
SELECT NAME, TARGET_ROWS_INSERTED, TARGET_ROWS_DELETED, ERROR_MESSAGE, LAST_REFRESH_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY
WHERE LAST_REFRESH_TIME >= DATEADD(minute, -30, CURRENT_TIMESTAMP())
  AND ERROR_MESSAGE IS NOT NULL;
