SELECT
  QUERY_ID, START_TIME, WAREHOUSE_NAME,
  EXECUTION_TIME/1000.0 AS exec_s,
  ROWS_PRODUCED,
  QUERY_TEXT
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
  END_TIME_RANGE_START => DATEADD('hour', -6, CURRENT_TIMESTAMP()),
  RESULT_LIMIT => 2000
))
WHERE EXECUTION_STATUS = 'SUCCESS'
ORDER BY exec_s DESC
LIMIT 50;
