SELECT QUERY_ID, START_TIME, WAREHOUSE_NAME,
       (QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME)/1000.0 AS queued_s,
       EXECUTION_TIME/1000.0 AS exec_s,
       QUERY_TEXT
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
  END_TIME_RANGE_START => DATEADD('hour', -1, CURRENT_TIMESTAMP()),
  RESULT_LIMIT => 500
))
WHERE USER_NAME = 'BI_SERVICE_USER'
ORDER BY START_TIME DESC;
