-- Spot queuing vs. execution for recent queries
SELECT
  QUERY_ID, WAREHOUSE_NAME,
  TOTAL_ELAPSED_TIME/1000 AS elapsed_s,
  (QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME)/1000 AS queued_s,
  EXECUTION_TIME/1000 AS exec_s,
  ROWS_PRODUCED
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
  END_TIME_RANGE_START => DATEADD('hour', -2, CURRENT_TIMESTAMP()),
  RESULT_LIMIT => 1000
))
ORDER BY elapsed_s DESC;

-- Warehouse load shape over time
SELECT *
FROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_LOAD_HISTORY(
  WAREHOUSE_NAME => 'WH_BI',
  START_TIME => DATEADD('hour', -2, CURRENT_TIMESTAMP())
))
ORDER BY START_TIME;
