SELECT
  QUERY_ID,
  START_TIME,
  USER_NAME,
  WAREHOUSE_NAME,
  TOTAL_ELAPSED_TIME/1000.0 AS elapsed_s,
  EXECUTION_TIME/1000.0     AS exec_s,
  (QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME)/1000.0 AS queued_s,
  ROWS_PRODUCED,
  QUERY_TEXT
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
  END_TIME_RANGE_START => DATEADD('hour', -6, CURRENT_TIMESTAMP()),
  RESULT_LIMIT => 2000
))
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 50;
