-- Domain role can SELECT all current & future tables in MART
GRANT USAGE ON DATABASE prod TO ROLE ROLE_FIN_READER;
GRANT USAGE ON SCHEMA prod.mart TO ROLE ROLE_FIN_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA prod.mart TO ROLE ROLE_FIN_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA prod.mart TO ROLE ROLE_FIN_READER;
