CREATE OR REPLACE RESOURCE MONITOR rm_hotfix
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE wh_hotfix SET RESOURCE_MONITOR = rm_hotfix;
