WITH d AS (
  SELECT TO_DATE(START_TIME) AS day, WAREHOUSE_NAME, SUM(CREDITS_USED) AS credits
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE START_TIME >= DATEADD(day,-14,CURRENT_TIMESTAMP())
  GROUP BY 1,2
),
b AS (
  SELECT WAREHOUSE_NAME,
         MEDIAN(credits) AS med7
  FROM d
  WHERE day < CURRENT_DATE()
  GROUP BY 1
)
SELECT d.WAREHOUSE_NAME, d.credits AS today, b.med7,
       (d.credits - b.med7) AS delta
FROM d JOIN b USING (WAREHOUSE_NAME)
WHERE d.day = CURRENT_DATE()
ORDER BY delta DESC;
