CREATE OR REPLACE VIEW ops.v_bad_patterns AS
SELECT QUERY_ID, USER_NAME, WAREHOUSE_NAME, BYTES_SCANNED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(minute,-10,CURRENT_TIMESTAMP())
  AND (QUERY_TEXT ILIKE '%SELECT * FROM%FACT_%'
       OR BYTES_SCANNED > 500*POWER(1024,3));
