CREATE OR REPLACE RESOURCE MONITOR rm_ad_hoc
  WITH CREDIT_QUOTA = 100
  FREQUENCY = DAILY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE wh_ad_hoc SET RESOURCE_MONITOR = rm_ad_hoc;
