-- Who still reads v1?
SELECT USER_NAME, ROLE_NAME, COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE DIRECT_OBJECTS_ACCESSED:objectName::string = 'MART.V_ORDERS_V1'
  AND QUERY_START_TIME >= DATEADD(day,-7,CURRENT_TIMESTAMP())
GROUP BY 1,2 ORDER BY 3 DESC;
