SELECT QUERY_ID, USER_NAME, ROLE_NAME, WAREHOUSE_NAME,
       BYTES_SCANNED/POWER(1024,3) AS gb_scanned,
       TOTAL_ELAPSED_TIME/1000 AS sec,
       LEFT(QUERY_TEXT, 300) AS txt
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_WAREHOUSE(RESULT_LIMIT=>1000))
WHERE START_TIME >= DATEADD(minute,-15,CURRENT_TIMESTAMP())
  AND BYTES_SCANNED > 200*POWER(1024,3)         -- >200 GB
ORDER BY BYTES_SCANNED DESC;
