SELECT
  COALESCE(PARSE_JSON(QUERY_TAG):team::string, 'unknown') AS team,
  ROLE_NAME,
  WAREHOUSE_NAME,
  SUM(CREDITS_USED_CLOUD_SERVICES + CREDITS_USED) AS credits,
  SUM(BYTES_SCANNED)/POWER(1024,3) AS gb_scanned
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(hour,-2,CURRENT_TIMESTAMP())
GROUP BY 1,2,3
ORDER BY credits DESC
LIMIT 20;
