SELECT COUNT(*) AS q, 
       IFF(QUERY_TEXT ILIKE '%SELECT *%', 'select_star','ok') AS smell
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(hour,-2,CURRENT_TIMESTAMP())
GROUP BY smell;
