SELECT DIRECT_OBJECTS_ACCESSED:objectName::string AS obj,
       COUNT(*) AS q, SUM(BYTES_SCANNED)/POWER(1024,3) AS gb
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD(hour,-2,CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY gb DESC
LIMIT 30;
