GRANT USAGE ON WAREHOUSE WH_BI  TO ROLE ROLE_WH_BI;
GRANT USAGE ON WAREHOUSE WH_ELT TO ROLE ROLE_WH_ELT;

-- Optionally restrict OPERATE (resume/suspend) to ops-only
GRANT OPERATE ON WAREHOUSE WH_ELT TO ROLE SYSADMIN;
