SELECT user_name, client_environment:AUTHENTICATOR::string AS authn
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE event_timestamp >= DATEADD(day,-7,CURRENT_TIMESTAMP())
  AND user_name IN (SELECT name FROM SNOWFLAKE.ACCOUNT_USAGE.USERS WHERE disabled='FALSE')
GROUP BY 1,2;
