-- Finance database and schema owned by ROLE_FIN_OWNER
CREATE DATABASE FINANCE;
GRANT OWNERSHIP ON DATABASE FINANCE TO ROLE_FIN_OWNER REVOKE CURRENT GRANTS;
GRANT USAGE ON DATABASE FINANCE TO ROLE_FIN_READER, ROLE_FIN_WRITER;

CREATE SCHEMA FINANCE.MART;
GRANT OWNERSHIP ON SCHEMA FINANCE.MART TO ROLE_FIN_OWNER REVOKE CURRENT GRANTS;
GRANT USAGE ON SCHEMA FINANCE.MART TO ROLE_FIN_READER, ROLE_FIN_WRITER;

-- Readers can SELECT; writers can DML
GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE.MART TO ROLE_FIN_READER;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA FINANCE.MART TO ROLE_FIN_WRITER;

-- Future grants keep it true for new tables/views
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE.MART TO ROLE_FIN_READER;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA FINANCE.MART TO ROLE_FIN_WRITER;
